### ISSUE TITLE
Showing ‘latest commit sha’ for some entities 

### ISSUE THREAD

**Issue by aptonline** [benct/lovelace-github-entity-row#1]
Just installed and if I enter more than one GitHub entity it displays that entities latest commit sha as opposed to the correct information. See below:

![B6B06D58-DB9B-4175-BDA3-32570EC05DC6](https://user-images.githubusercontent.com/190136/73440566-61296d80-4349-11ea-936b-274a2d46346e.jpeg)

Here is my config (excuse the screenshot but I can’t copy and paste from the editor in iOS as it’s broken)

![C79BEEE9-2ECF-451F-9749-58247C999872](https://user-images.githubusercontent.com/190136/73440698-b2396180-4349-11ea-8ad7-441664f5b2ae.jpeg)

Running Home Assistant 0.104.3

**Comment by benct** [comment]
Because these are separate entity rows, you need to specify a `type: 'custom:github-entity-row'` on all the entities. So just add that line under each `name` there, and it should work :)

**Comment by aptonline** [comment]
That’s great, thanks for pointing that out for me. All working now 👍🏼
