### ISSUE TITLE
Incorrect Issue Count

### ISSUE THREAD

**Issue by jeremywillans** [benct/lovelace-github-entity-row#2]
Great plugin!

It seems that the issues count is including open PRs?

![image](https://user-images.githubusercontent.com/31495062/86856946-c6f00180-c100-11ea-8272-f269920890b3.png)

![image](https://user-images.githubusercontent.com/31495062/86856961-cf483c80-c100-11ea-885a-e81987b640ea.png)

**Comment by benct** [comment]
Not much I can do about that I'm afraid, as the underlying github integration in the HA core provides the numbers. These numbers are actually correct though, because a PR is an issue (just with an additional code patch).
