### ISSUE TITLE
Where do i get the Entities from?

### ISSUE THREAD

**Issue by MrDrache333** [benct/lovelace-github-entity-row#3]
I've installed this repo from HACS and added your demo configuration to my Lovelace dashboard. But i only see this error. Where do i get those entities from?![image](https://user-images.githubusercontent.com/22854641/105609592-9cb71600-5daa-11eb-9be6-c1906890f392.png)

**Comment by ioios-io** [comment]
In case the OP didn't ever get an answer, there is a GitHub integration inside HA. You will need to get an API key for access but once done, the sensors appear soon after.

**Comment by MrDrache333** [comment]
Oh. Nevermind. Thanks
