### ISSUE TITLE
Breaks with HASS v2022.2

### ISSUE THREAD

**Issue by jazzyisj** [benct/lovelace-github-entity-row#4]
This is going to break! The revamped github integration splits all the properties into separate sensors.

https://rc.home-assistant.io/integrations/github/

Love the card, hope you're able to rework it for the new format.

**Comment by WarC0zes** [comment]
It's broken! as you say now there are several entities for a repo. 
It would be nice to be able to fix your card, I love it.

**Comment by benct** [comment]
I'll try to see if some kind of fix is possible as soon as I can.

Could you provide me with a copy/screenshot of the new sensor values and attributes (`<your-ha>/developer-tools/state`)? Is there still a "main" entity, or just the separate sensors?

**Comment by WarC0zes** [comment]
there are 9 entities per repo created :-1: .  Look for meross homeassistant.
![meross git1](https://user-images.githubusercontent.com/91471397/152351770-e2890098-9acd-487a-b55b-edad147b6ed3.jpg)
![meross git2](https://user-images.githubusercontent.com/91471397/152351824-b4fec30e-1171-40b8-87d1-c7caffddafa1.jpg)

**Comment by benct** [comment]
Should be supported in version `2.0.0` (see readme for config changes).

**Comment by jazzyisj** [comment]
Back in business!  Thanks!
